/**
 * `isolateBidi` bidirectional-isolation wrapper test suite — 4 tiers.
 *
 * WHAT THIS LOCKS
 *   1. BRANCH COMPLETENESS — standard string isolation wrapping with FSI
 *      (U+2066, FIRST-STRONG ISOLATE) prefix and PDI (U+2069, POP DIRECTIONAL
 *      ISOLATE) suffix. Exact code point verification (0x2066 at index 0,
 *      0x2069 at index end).
 *   2. BOUNDARY CONDITIONS — empty strings, single-character strings,
 *      whitespace-only strings, and masked names generated by `maskFullName`.
 *   3. UNICODE, BIDI & MIXED DIRECTIONALITY — Arabic RTL names, mixed
 *      LTR/RTL with digits/symbols, complex graphemes (combining marks,
 *      ZWJ emoji sequences, skin tone modifiers, flag pairs), and strings with
 *      pre-existing bidi control codes (FSI, PDI, LRM, RLM).
 *   4. DETERMINISM & INVARIANTS — determinism across repeated calls, exact
 *      length invariant (`output.length === input.length + 2`), exact
 *      inner payload preservation (`output.slice(1, -1) === input`), and
 *      100 seeded pseudo-random fixtures.
 *
 * Pure unit tier — NO server boot, NO network, NO DB. Runs via the mandated
 * runner: `bun run test/scripts/run-test.ts shared/lib/isolate-bidi.test.ts`.
 */

import { describe, expect, test } from "bun:test";
import { isolateBidi } from "@/shared/lib/isolate-bidi";
import { maskFullName } from "@/shared/lib/mask-full-name";

const FSI_CODE = 0x2066; // U+2066 FIRST-STRONG ISOLATE
const PDI_CODE = 0x2069; // U+2069 POP DIRECTIONAL ISOLATE
const FSI_CHAR = "\u2066";
const PDI_CHAR = "\u2069";

// ─── Tier 1: branch completeness & basic isolation ──────────────────────────

describe("isolateBidi — Tier 1: branch completeness & basic isolation", () => {
  test("wraps plain LTR name in FSI prefix and PDI suffix", () => {
    const input = "John Doe";
    const result = isolateBidi(input);

    expect(result).toBe(`${FSI_CHAR}John Doe${PDI_CHAR}`);
    expect(result.startsWith(FSI_CHAR)).toBe(true);
    expect(result.endsWith(PDI_CHAR)).toBe(true);
  });

  test("verifies exact Unicode code points for FSI (0x2066) and PDI (0x2069)", () => {
    const input = "Alice";
    const result = isolateBidi(input);

    expect(result.codePointAt(0)).toBe(FSI_CODE);
    expect(result.codePointAt(result.length - 1)).toBe(PDI_CODE);
  });

  test("preserves internal string content exactly between FSI and PDI", () => {
    const input = "Sample Display Name";
    const result = isolateBidi(input);

    const inner = result.slice(1, -1);
    expect(inner).toBe(input);
  });
});

// ─── Tier 2: boundary conditions ─────────────────────────────────────────────

describe("isolateBidi — Tier 2: boundary conditions", () => {
  test("handles empty string input by returning FSI + PDI island only", () => {
    const result = isolateBidi("");
    expect(result).toBe(`${FSI_CHAR}${PDI_CHAR}`);
    expect(result).toHaveLength(2);
    expect(result.charCodeAt(0)).toBe(FSI_CODE);
    expect(result.charCodeAt(1)).toBe(PDI_CODE);
  });

  test("handles single-character LTR, RTL, digit, and symbol inputs", () => {
    expect(isolateBidi("A")).toBe(`${FSI_CHAR}A${PDI_CHAR}`);
    expect(isolateBidi("ع")).toBe(`${FSI_CHAR}ع${PDI_CHAR}`);
    expect(isolateBidi("1")).toBe(`${FSI_CHAR}1${PDI_CHAR}`);
    expect(isolateBidi("#")).toBe(`${FSI_CHAR}#${PDI_CHAR}`);
  });

  test("handles whitespace-only inputs including tabs, newlines, and NBSP", () => {
    expect(isolateBidi(" ")).toBe(`${FSI_CHAR} ${PDI_CHAR}`);
    expect(isolateBidi("   ")).toBe(`${FSI_CHAR}   ${PDI_CHAR}`);
    expect(isolateBidi("\t\n\r")).toBe(`${FSI_CHAR}\t\n\r${PDI_CHAR}`);
    expect(isolateBidi("\u00A0\u2003")).toBe(`${FSI_CHAR}\u00A0\u2003${PDI_CHAR}`);
  });

  test("wraps masked name output from maskFullName seamlessly", () => {
    const maskedSingle = maskFullName("Yusuf");
    expect(isolateBidi(maskedSingle)).toBe(`${FSI_CHAR}Y***${PDI_CHAR}`);

    const maskedMulti = maskFullName("أحمد محمد");
    expect(isolateBidi(maskedMulti)).toBe(`${FSI_CHAR}أ*** م***${PDI_CHAR}`);
  });
});

// ─── Tier 3: Unicode graphemes, RTL & mixed directionality ───────────────────

describe("isolateBidi — Tier 3: Unicode graphemes, RTL & mixed directionality", () => {
  test("wraps pure Arabic RTL display names without altering character order", () => {
    const arabicName = "أحمد عبد الله";
    const result = isolateBidi(arabicName);

    expect(result).toBe(`${FSI_CHAR}أحمد عبد الله${PDI_CHAR}`);
    expect(result.slice(1, -1)).toBe(arabicName);
  });

  test("wraps mixed LTR/RTL names with numbers and neutral punctuation", () => {
    const mixed = "John - أحمد (123)";
    const result = isolateBidi(mixed);

    expect(result).toBe(`${FSI_CHAR}John - أحمد (123)${PDI_CHAR}`);
  });

  test("handles complex multi-code-point graphemes and ZWJ emoji sequences", () => {
    const zwjEmoji = "👨‍👩‍👧‍👦";
    expect(isolateBidi(zwjEmoji)).toBe(`${FSI_CHAR}👨‍👩‍👧‍👦${PDI_CHAR}`);

    const skinTone = "👍🏽";
    expect(isolateBidi(skinTone)).toBe(`${FSI_CHAR}👍🏽${PDI_CHAR}`);

    const flag = "🇪🇬";
    expect(isolateBidi(flag)).toBe(`${FSI_CHAR}🇪🇬${PDI_CHAR}`);
  });

  test("handles decomposed combining marks and lone surrogates without error", () => {
    const combining = "e\u0301milie";
    expect(isolateBidi(combining)).toBe(`${FSI_CHAR}e\u0301milie${PDI_CHAR}`);

    const loneHighSurrogate = "\uD83D";
    expect(isolateBidi(loneHighSurrogate)).toBe(`${FSI_CHAR}\uD83D${PDI_CHAR}`);
  });

  test("safely wraps strings containing embedded bidi marks (LRM, RLM, FSI, PDI)", () => {
    const embedded = "\u200EJohn \u200Fأحمد \u2066Nested\u2069";
    const result = isolateBidi(embedded);

    expect(result).toBe(`${FSI_CHAR}\u200EJohn \u200Fأحمد \u2066Nested\u2069${PDI_CHAR}`);
    expect(result.slice(1, -1)).toBe(embedded);
  });
});

// ─── Tier 4: determinism & invariant properties ──────────────────────────────

/** Deterministic xorshift32 PRNG for fixture generation. */
function createSeededRandom(seed: number): () => number {
  let state = seed;
  return () => {
    state ^= state << 13;
    state ^= state >>> 17;
    state ^= state << 5;
    return (state >>> 0) / 2 ** 32;
  };
}

describe("isolateBidi — Tier 4: determinism & invariant properties", () => {
  test("function is purely deterministic and returns identical outputs for identical inputs", () => {
    const input = "Dr. Mohamed El-Sayed";
    const firstCall = isolateBidi(input);
    const secondCall = isolateBidi(input);

    expect(firstCall).toBe(secondCall);
  });

  test("output length invariant: result length is always input length + 2", () => {
    const testCases = ["", "A", "Short Name", "أحمد محمد علي", "👨‍👩‍👧‍👦 Family Name", " \t\n ", "e\u0301milie"];

    for (const text of testCases) {
      expect(isolateBidi(text)).toHaveLength(text.length + 2);
    }
  });

  test("slice invariant: stripping the first and last character restores original string exactly", () => {
    const testCases = [
      "",
      "John",
      "أحمد",
      "12345",
      "!@#$%^&*",
      "Mixed English العربية 42",
      "\u2066Already Isolated\u2069",
    ];

    for (const text of testCases) {
      const isolated = isolateBidi(text);
      expect(isolated.slice(1, -1)).toBe(text);
    }
  });

  test("100 seeded random fixtures: verifies length invariant, boundary codes, and inner match", () => {
    const CHAR_POOL = [
      "A",
      "b",
      "Z",
      "أ",
      "ح",
      "م",
      "د",
      "1",
      "9",
      " ",
      "-",
      "_",
      "👨‍👩‍👧‍👦",
      "e\u0301",
      "\u200E",
      "\u200F",
    ];
    const random = createSeededRandom(0x42b1d0);

    for (let iteration = 0; iteration < 100; iteration++) {
      const strLength = Math.floor(random() * 30);
      let fixture = "";
      for (let i = 0; i < strLength; i++) {
        fixture += CHAR_POOL[Math.floor(random() * CHAR_POOL.length)];
      }

      const result = isolateBidi(fixture);

      // Invariant 1: length is fixture.length + 2
      expect(result).toHaveLength(fixture.length + 2);

      // Invariant 2: prefix code point is 0x2066 and suffix code point is 0x2069
      expect(result.codePointAt(0)).toBe(FSI_CODE);
      expect(result.codePointAt(result.length - 1)).toBe(PDI_CODE);

      // Invariant 3: inner content is strictly equal to the original fixture
      expect(result.slice(1, -1)).toBe(fixture);
    }
  });
});
