import type { IanaTimezoneLabels } from "@/scripts/iana-timezone-generator/labels";

function ianaIdToEnumKey(ianaId: string): string {
  return ianaId.replace(/\//g, "_").replace(/-/g, "_").replace(/\+/g, "_plus_");
}

export function buildSharedTerritoriesFile(territories: Record<string, string | null>): string {
  const entries = Object.entries(territories)
    .map(([id, code]) => `  "${id}": ${code === null ? "null" : JSON.stringify(code)},`)
    .join("\n");
  return `// AUTO-GENERATED by scripts/generate-iana-timezone-enum.ts — do not edit manually
// Regenerate: bun run generate:iana-timezones

import type { IanaTimezoneId } from "@/shared/constants/iana-timezones";

export const IANA_TIMEZONE_TERRITORY_CODES: Record<IanaTimezoneId, string | null> = {
${entries}
};
`;
}

export function buildSharedConstantsFile(ids: string[]): string {
  const lines = ids.map(id => `  "${id}",`).join("\n");
  return `// AUTO-GENERATED by scripts/generate-iana-timezone-enum.ts — do not edit manually
// Regenerate: bun run generate:iana-timezones

export const IANA_TIMEZONE_IDS = [
${lines}
] as const;

export type IanaTimezoneId = (typeof IANA_TIMEZONE_IDS)[number];
`;
}

export function buildSharedLabelsFile(labels: Record<string, IanaTimezoneLabels>): string {
  const entries = Object.entries(labels)
    .map(([id, value]) => `  "${id}": { en: ${JSON.stringify(value.en)}, ar: ${JSON.stringify(value.ar)} },`)
    .join("\n");

  return `// AUTO-GENERATED by scripts/generate-iana-timezone-enum.ts — do not edit manually
// Regenerate: bun run generate:iana-timezones

import type { IanaTimezoneId } from "@/shared/constants/iana-timezones";

export type IanaTimezoneLabels = {
  readonly en: string;
  readonly ar: string;
};

export const IANA_TIMEZONE_LABELS: Record<IanaTimezoneId, IanaTimezoneLabels> = {
${entries}
};
`;
}

export function buildBackendEnumFile(ids: string[]): string {
  const entries = ids
    .map(id => {
      const key = ianaIdToEnumKey(id);
      return `  ${key} = "${id}",`;
    })
    .join("\n");

  return `// AUTO-GENERATED by scripts/generate-iana-timezone-enum.ts — do not edit manually
// Regenerate: bun run generate:iana-timezones

export enum IanaTimezone {
${entries}
}
`;
}
