"use client";

import { useRouter, useSearchParams } from "next/navigation";
import { type ReactNode, useEffect } from "react";
import { useAuth } from "@/frontend/hooks/auth";
import { resolvePostAuthTarget } from "@/frontend/lib/auth/roleDashboardRoute";
import { AuthBrandPanel, AuthFormPanel, AuthLayoutStyles } from "@/frontend/views/auth/layout";

/**
 * Auth route group layout — branded **2-column split-screen** wrapper for
 * `/login` + `/register`.
 *
 * The route group `(auth)` is a Next.js organizational folder — the parens
 * keep these routes out of the URL path (so `/login` not `/auth/login`).
 *
 * Design (Midnight Blue + Copper brand identity):
 *  - **Left brand panel** (~40% width, hidden on `xs`/`sm`): full-height
 *    midnight-blue gradient with copper accent glow + Islamic geometric
 *    tessellation overlay. Contains brand wordmark, tagline, marketing
 *    pitch, and a decorative book/khatam motif. See `AuthBrandPanel`.
 *  - **Right form panel** (~60% width, always visible): plain
 *    `background.default` (NO gradient — form sits directly on the panel).
 *    Locale switcher pinned top-right, content centered vertically.
 *    See `AuthFormPanel`.
 *  - On mobile (`xs`/`sm`): brand panel collapses away; the form panel
 *    takes the full viewport. A slim brand header banner renders above
 *    the form so the brand identity is still present.
 *  - The 2-column → 1-column responsive rules live in `AuthLayoutStyles`.
 *
 * The AppClientProviders (Apollo + Auth + Theme) are already mounted in
 * `app/layout.tsx` (root layout), so auth pages inherit them — no provider
 * re-mounting here.
 *
 * DEV2-CORE — Login page auto-redirect (redirect-loop fix):
 *  - If `isAuthenticated` is true (from `useAuth()`), redirect to the
 *    `?redirect=` param (if safe) or the caller's ROLE-SPECIFIC dashboard.
 *  - The redirect runs in a `useEffect` (after hydration) to avoid SSR/CSR
 *    mismatch. `useSearchParams` reads the `?redirect=` param.
 *
 * Implementation note: theme colors are accessed via MUI v9 CSS variables
 * (`var(--mui-palette-*)`) generated by `cssVariables: true` in `theme.ts`.
 * This satisfies the AGENTS.md "no hardcoded colors" rule without requiring
 * a `useTheme()` call (the brand panel uses inline `<style>` + inline
 * `style` attributes, which need plain CSS values, not `sx` callbacks).
 */
export default function AuthLayout({ children }: { readonly children: ReactNode }) {
  const { isAuthenticated, isLoading, user } = useAuth();
  const router = useRouter();
  const searchParams = useSearchParams();

  // DEV2-CORE: auto-redirect authenticated users away from /login (and
  // /register). Skipped during `isLoading` so we don't redirect a user
  // whose session is still being restored (e.g. via `refreshToken`).
  // Mirrors the `DashboardLayout` auth-redirect pattern.
  //
  // The fallback target is the caller's ROLE-SPECIFIC dashboard — never
  // bare "/dashboard". Through the z.ai preview gateway that path is
  // 301'd to "/dashboard/" while Next.js 308s it back — a browser
  // redirect loop (see `frontend/lib/auth/roleDashboardRoute.ts`).
  // This effect also owns the no-param post-login bounce: LoginForm
  // deliberately skips navigation when no `?redirect=` param is present
  // and defers to this role-aware replace (fresh `user` from context).
  useEffect(() => {
    if (isLoading) return;
    if (!isAuthenticated) return;
    const redirectParam = searchParams.get("redirect");
    router.replace(resolvePostAuthTarget(redirectParam, user?.role));
  }, [isAuthenticated, isLoading, router, searchParams, user]);

  return (
    <main className="auth-shell">
      <AuthLayoutStyles />

      {/* === Left brand panel (md+ only) === */}
      <AuthBrandPanel />

      {/* === Right form panel === */}
      <AuthFormPanel>{children}</AuthFormPanel>
    </main>
  );
}
