"use client";

import { useRouter, useSearchParams } from "next/navigation";
import { type ReactNode, useEffect } from "react";
import { LocaleSwitcher } from "@/frontend/components/LocaleSwitcher";
import { SiteFooter } from "@/frontend/components/SiteFooter";
import { useAuth } from "@/frontend/hooks/useAuth";
import { resolvePostAuthTarget } from "@/frontend/lib/auth/roleDashboardRoute";
import { Auth, useAppTranslation } from "@/shared/locale";

/**
 * Auth route group layout — branded **2-column split-screen** wrapper for
 * `/login` + `/register`.
 *
 * The route group `(auth)` is a Next.js organizational folder — the parens
 * keep these routes out of the URL path (so `/login` not `/auth/login`).
 *
 * Design (Midnight Blue + Copper brand identity):
 *  - **Left brand panel** (~40% width, hidden on `xs`/`sm`): full-height
 *    midnight-blue gradient with copper accent glow + Islamic geometric
 *    tessellation overlay. Contains brand wordmark, tagline, marketing
 *    pitch, and a decorative book/khatam motif.
 *  - **Right form panel** (~60% width, always visible): plain
 *    `background.default` (NO gradient — form sits directly on the panel).
 *    Locale switcher pinned top-right, content centered vertically.
 *  - On mobile (`xs`/`sm`): brand panel collapses away; the form panel
 *    takes the full viewport. A slim brand header banner renders above
 *    the form so the brand identity is still present.
 *
 * The AppClientProviders (Apollo + Auth + Theme) are already mounted in
 * `app/layout.tsx` (root layout), so auth pages inherit them — no provider
 * re-mounting here.
 *
 * DEV2-CORE — Login page auto-redirect (redirect-loop fix):
 *  - If `isAuthenticated` is true (from `useAuth()`), redirect to the
 *    `?redirect=` param (if safe) or the caller's ROLE-SPECIFIC dashboard.
 *  - The redirect runs in a `useEffect` (after hydration) to avoid SSR/CSR
 *    mismatch. `useSearchParams` reads the `?redirect=` param.
 *
 * Client component (DASHBOARD-1): all user-facing strings come from
 * `useAppTranslation(Auth)` so the brand panel + trust badges render in the
 * active locale. The "Kottaby Academy" brand name is exempt from i18n per
 * AGENTS.md (brand identity, not translated).
 *
 * Implementation note: theme colors are accessed via MUI v9 CSS variables
 * (`var(--mui-palette-*)`) generated by `cssVariables: true` in `theme.ts`.
 * This satisfies the AGENTS.md "no hardcoded colors" rule without requiring
 * a `useTheme()` call (the brand panel uses inline `<style>` + inline
 * `style` attributes, which need plain CSS values, not `sx` callbacks).
 */
export default function AuthLayout({ children }: { readonly children: ReactNode }) {
  const t = useAppTranslation(Auth);
  const { isAuthenticated, isLoading, user } = useAuth();
  const router = useRouter();
  const searchParams = useSearchParams();

  // DEV2-CORE: auto-redirect authenticated users away from /login (and
  // /register). Skipped during `isLoading` so we don't redirect a user
  // whose session is still being restored (e.g. via `refreshToken`).
  // Mirrors the `DashboardLayout` auth-redirect pattern.
  //
  // The fallback target is the caller's ROLE-SPECIFIC dashboard — never
  // bare "/dashboard". Through the z.ai preview gateway that path is
  // 301'd to "/dashboard/" while Next.js 308s it back — a browser
  // redirect loop (see `frontend/lib/auth/roleDashboardRoute.ts`).
  // This effect also owns the no-param post-login bounce: LoginForm
  // deliberately skips navigation when no `?redirect=` param is present
  // and defers to this role-aware replace (fresh `user` from context).
  useEffect(() => {
    if (isLoading) return;
    if (!isAuthenticated) return;
    const redirectParam = searchParams.get("redirect");
    router.replace(resolvePostAuthTarget(redirectParam, user?.role));
  }, [isAuthenticated, isLoading, router, searchParams, user]);

  return (
    <main className="auth-shell">
      {/* Responsive layout rules — single source of truth for the
          2-column → 1-column collapse. Kept inline (no CSS module) so the
          rule ships with the markup and stays scoped to this layout. */}
      <style>{`
        .auth-shell {
          min-height: 100vh;
          display: grid;
          grid-template-columns: minmax(0, 1fr);
          position: relative;
          overflow-y: auto;
          background-color: var(--mui-palette-background-default);
        }
        .auth-brand-panel {
          display: none;
          flex-direction: column;
          justify-content: space-between;
          padding: 48px 56px;
          position: relative;
          overflow: hidden;
          isolation: isolate;
          background: linear-gradient(160deg,
            var(--mui-palette-primary-dark) 0%,
            var(--mui-palette-primary-main) 45%,
            var(--mui-palette-primary-dark) 100%);
          color: var(--mui-palette-onPrimary);
        }
        .auth-form-panel {
          position: relative;
          display: flex;
          flex-direction: column;
          min-height: 100vh;
          background-color: var(--mui-palette-background-default);
          color: var(--mui-palette-text-primary);
        }
        .auth-mobile-banner {
          display: flex;
          align-items: center;
          justify-content: center;
          gap: 10px;
          padding: 14px 16px;
          background: linear-gradient(90deg,
            var(--mui-palette-primary-dark),
            var(--mui-palette-primary-main));
          color: var(--mui-palette-onPrimary);
        }
        @media (min-width: 900px) {
          .auth-shell { grid-template-columns: 2fr 3fr; }
          .auth-brand-panel { display: flex; }
          .auth-mobile-banner { display: none; }
        }
      `}</style>

      {/* === Left brand panel (md+ only) === */}
      <aside className="auth-brand-panel">
        {/* Decorative Islamic geometric tessellation overlay (khatam
            suggested via two overlapping rotated grids). Pure CSS — no
            external SVG asset. Low opacity so it doesn't compete. */}
        <div
          aria-hidden
          style={{
            position: "absolute",
            inset: 0,
            opacity: 0.08,
            pointerEvents: "none",
            backgroundImage:
              "repeating-linear-gradient(45deg, transparent, transparent 28px, var(--mui-palette-secondary-light) 28px, var(--mui-palette-secondary-light) 30px), repeating-linear-gradient(-45deg, transparent, transparent 28px, var(--mui-palette-secondary-light) 28px, var(--mui-palette-secondary-light) 30px)",
          }}
        />
        {/* Copper radial glow accent (top-right) */}
        <div
          aria-hidden
          style={{
            position: "absolute",
            top: "-20%",
            right: "-20%",
            width: "70%",
            height: "70%",
            background: "radial-gradient(circle, var(--mui-palette-secondary-main) 0%, transparent 65%)",
            opacity: 0.25,
            pointerEvents: "none",
          }}
        />
        {/* Secondary glow bottom-left for depth */}
        <div
          aria-hidden
          style={{
            position: "absolute",
            bottom: "-25%",
            left: "-15%",
            width: "60%",
            height: "60%",
            background: "radial-gradient(circle, var(--mui-palette-primary-light) 0%, transparent 70%)",
            opacity: 0.2,
            pointerEvents: "none",
          }}
        />

        {/* === Top: Brand wordmark === */}
        <div style={{ position: "relative", zIndex: 1, display: "flex", alignItems: "center", gap: 12 }}>
          <BrandMark />
          <div style={{ display: "flex", flexDirection: "column" }}>
            <span style={{ fontSize: 22, fontWeight: 700, letterSpacing: "-0.01em", lineHeight: 1.1 }}>
              Kottaby Academy
            </span>
            <span
              style={{
                fontSize: 12,
                fontWeight: 600,
                letterSpacing: "0.14em",
                textTransform: "uppercase",
                opacity: 0.75,
              }}
            >
              {t.brandTagline}
            </span>
          </div>
        </div>

        {/* === Middle: Marketing pitch + decorative book motif === */}
        <div style={{ position: "relative", zIndex: 1, maxWidth: 440 }}>
          <BookMotif />
          {/* This decorative marketing headline rendered as a bare
              <h2> BEFORE the form's <h1>, inverting the document outline on
              every auth page. Same look as a paragraph — the form title
              stays the page's single top-level heading. */}
          <p
            style={{
              margin: "32px 0 16px",
              fontFamily: "inherit",
              fontSize: 32,
              fontWeight: 700,
              lineHeight: 1.2,
              letterSpacing: "-0.02em",
            }}
          >
            {t.brandPitchTitle}
          </p>
          <p
            style={{
              margin: 0,
              fontSize: 16,
              lineHeight: 1.6,
              opacity: 0.85,
              maxWidth: 380,
            }}
          >
            {t.brandPitchBody}
          </p>
        </div>

        {/* === Bottom: Trust badges === */}
        <div
          style={{
            position: "relative",
            zIndex: 1,
            display: "flex",
            alignItems: "center",
            gap: 24,
            fontSize: 13,
            opacity: 0.75,
            flexWrap: "wrap",
          }}
        >
          <TrustItem label={t.trustVerifiedShuyukh} />
          <TrustItem label={t.trustQiraat} />
          <TrustItem label={t.trustSecurePrivate} />
        </div>
      </aside>

      {/* === Right form panel === */}
      <section className="auth-form-panel">
        {/* Slim mobile brand banner (xs/sm only) */}
        <div className="auth-mobile-banner">
          <BrandMark size={28} />
          <span style={{ fontSize: 16, fontWeight: 700, letterSpacing: "-0.01em" }}>Kottaby Academy</span>
        </div>

        {/* Top-right locale switcher */}
        <div
          style={{
            position: "absolute",
            top: 16,
            insetInlineEnd: 16,
            zIndex: 10,
          }}
        >
          <LocaleSwitcher />
        </div>

        {/* Scrollable form container */}
        <div
          style={{
            flex: 1,
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            padding: "32px 24px",
            width: "100%",
            maxWidth: 720,
            margin: "0 auto",
          }}
        >
          {children}
        </div>

        {/* Sticky footer — pushed to bottom by flex:1 above. Copper-topped
            midnight-blue footer matches the brand panel. */}
        <SiteFooter />
      </section>
    </main>
  );
}

/** Brand mark — an inline SVG monogram (open book + crescent) in copper. */
function BrandMark({ size = 40 }: { readonly size?: number }) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 48 48"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      style={{ flexShrink: 0 }}
    >
      {/* Outer circle (copper ring) */}
      <circle cx="24" cy="24" r="22" stroke="var(--mui-palette-secondary-light)" strokeWidth="1.5" opacity="0.55" />
      {/* Open book pages */}
      <path
        d="M12 16c4-2 8-2 12 0 4-2 8-2 12 0v18c-4-2-8-2-12 0-4-2-8-2-12 0V16z"
        fill="var(--mui-palette-secondary-light)"
        opacity="0.95"
      />
      {/* Book spine */}
      <path d="M24 16v18" stroke="var(--mui-palette-primary-dark)" strokeWidth="1.5" />
      {/* Crescent accent (top-right) */}
      <path d="M34 12a4 4 0 1 1-3.5 6 3 3 0 1 0 3.5-6z" fill="var(--mui-palette-onPrimary)" opacity="0.9" />
    </svg>
  );
}

/** Large decorative book + 8-pointed-star (khatam) motif for the brand panel. */
function BookMotif() {
  return (
    <svg
      width="84"
      height="84"
      viewBox="0 0 96 96"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      style={{ opacity: 0.95 }}
    >
      {/* Geometric 8-pointed star (khatam) — two overlapping squares */}
      <rect
        x="20"
        y="20"
        width="56"
        height="56"
        stroke="var(--mui-palette-secondary-light)"
        strokeWidth="1.5"
        opacity="0.7"
        transform="rotate(45 48 48)"
      />
      <rect
        x="20"
        y="20"
        width="56"
        height="56"
        stroke="var(--mui-palette-secondary-light)"
        strokeWidth="1.5"
        opacity="0.7"
      />
      {/* Central book icon */}
      <path
        d="M24 36c8-4 16-4 24 0 8-4 16-4 24 0v32c-8-4-16-4-24 0-8-4-16-4-24 0V36z"
        fill="var(--mui-palette-secondary-main)"
        opacity="0.9"
      />
      <path d="M48 36v32" stroke="var(--mui-palette-primary-dark)" strokeWidth="2" />
      {/* Decorative dots */}
      <circle cx="48" cy="20" r="3" fill="var(--mui-palette-secondary-light)" />
      <circle cx="48" cy="76" r="3" fill="var(--mui-palette-secondary-light)" />
    </svg>
  );
}

/** Trust badge — small inline dot + label. */
function TrustItem({ label }: { readonly label: string }) {
  return (
    <span style={{ display: "inline-flex", alignItems: "center", gap: 6 }}>
      <span
        style={{
          width: 6,
          height: 6,
          borderRadius: "50%",
          backgroundColor: "var(--mui-palette-secondary-light)",
          display: "inline-block",
        }}
      />
      {label}
    </span>
  );
}
